FROM golang:latest AS builder

WORKDIR /app

RUN export GO111MODULE=on

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -v -o ./reports ./cmd/reports

FROM alpine:latest AS runner

COPY --from=builder /app/reports .
COPY --from=builder /app/config.yaml ./config.yaml

EXPOSE 8080 9000 9001 9200

CMD [ "./reports", "web-api" ]