version: "3.7"
services:
  back:
    build:
      context: ./
      dockerfile: ./Dockerfile_back
      args:
        - NO_CACHE=${CACHE_BUSTER:-1}
    restart: always
    container_name: backend_reports
    depends_on:
      - elasticsearch
      - kibana
      - minio
    ports:
      - "8080:8080"
    networks:
      - ps

  elasticsearch:
    image: bitnami/elasticsearch:7.17.10
    container_name: elasticsearch-diploma
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic_vol:/usr/share/elasticsearch/data
    networks:
      - ps

  kibana:
    image: bitnami/kibana:7.17.10
    container_name: kibana-diploma
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    deploy:
      resources:
        limits:
          cpus: "2.0"
        reservations:
          cpus: "1.0"
    depends_on:
      - elasticsearch
    networks:
      - ps
    
  minio:
    image: minio/minio
    container_name: minio-diploma
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_vol:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - ps

volumes:
  elastic_vol:
  minio_vol:

networks:
  ps:
